# Generated by Django 5.1.2 on 2024-11-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answerlike_answer_alter_questionlike_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(related_name='tags', to='app.question'),
        ),
    ]
