# Generated by Django 5.1.2 on 2024-11-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
    ]
